name: data
on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.morph.io/philippnagel/gwatch-scraper/data.json?key=XlA5bxJ2LEliNd0GJBQz&query=select%20*%20from%20%22certificates%22
          downloaded_filename: data.json
